version: '3'
services:
  jvs-apply-document:
    build:
      context: ./document-mgr
    restart: always
    volumes:
      - ./data/nacos/:/root/nacos/config
    image: 0glg0/document-mgr:${JVSVERSION}
    container_name: document-mgr
    networks:
      - jvs_jvs
    external_links:
      - gateway

networks:
  jvs_jvs:
    external: true
